Update using_grunt.md
To prevent:
```
$ grunt clean
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'd:\OSPanel\domains\mg2as/dev/tools/grunt/configs/local-themes'
Warning: Task "clean" not found. Use --force to continue.

Aborted due to warnings.
```